// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/threejs/three-css3drenderer.d.ts
declare namespace THREE {
    class CSS3DObject extends Object3D {
        constructor(element: any);

        element: any;
    }

    class CSS3DSprite extends CSS3DObject {
        constructor(element: any);

    }


    class CSS3DRenderer {
        constructor();

        domElement:HTMLElement;

        setSize(width: number, height: number): void;
        render(scene: THREE.Scene, camera: THREE.Camera): void;
    }
}
